baseURL = "https://okyzyr.github.io/ARMzilla/"
languageCode = "pl"
title = "ARMzilla"
theme = "PaperMod"
publishDir = "docs"

[pagination]
  pagerSize = 5


[params]
  author = "Okyzyr"
  description = "Projekt ramienia – wymyślenie koła na nowo."
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[[menu.main]]
  name = "Strona główna"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posty"
  url = "/posts/"
  weight = 2
